"use client";

import { useCompletion } from "@ai-sdk/react";
import { useEffect, useState, useCallback, useRef } from "react";
import { StyleSelector } from "./StyleSelector";
import { StreamingContent } from "./StreamingContent";
import { MarkdownSource } from "./MarkdownSource";
import { CopyPageDropdown } from "./CopyPageDropdown";
import { loadStyleOptions, saveStyleOptions } from "@/lib/style-storage";
import type { PostMeta, StyleOptions } from "@/lib/types";

interface PostPageClientProps {
  meta: PostMeta;
  rawContent: string;
}

const defaultStyle: StyleOptions = {
  language: "ja",
  tone: "neutral",
  detail: "standard",
};

export function PostPageClient({ meta, rawContent }: PostPageClientProps) {
  const [style, setStyle] = useState<StyleOptions>(defaultStyle);
  const [ready, setReady] = useState(false);
  const [showOriginal, setShowOriginal] = useState(false);
  const [viewingMarkdown, setViewingMarkdown] = useState(false);
  const initializedRef = useRef(false);

  const { completion, isLoading, complete, stop, error } = useCompletion({
    api: "/api/generate",
    body: {
      slug: meta.slug,
      language: style.language,
      tone: style.tone,
      detail: style.detail,
    },
    streamProtocol: "text",
  });

  const generate = useCallback(() => {
    complete("");
  }, [complete]);

  // Load saved preferences then auto-generate
  useEffect(() => {
    if (initializedRef.current) return;
    initializedRef.current = true;
    loadStyleOptions().then((saved) => {
      if (saved) setStyle(saved);
      setReady(true);
    });
  }, []);

  // Auto-generate once ready
  useEffect(() => {
    if (ready) generate();
  }, [ready, generate]);

  // Re-generate when style changes (via useEffect to ensure body is updated)
  const styleChangedByUser = useRef(false);

  function handleStyleChange(newStyle: StyleOptions) {
    styleChangedByUser.current = true;
    setStyle(newStyle);
    saveStyleOptions(newStyle);
  }

  useEffect(() => {
    if (styleChangedByUser.current) {
      styleChangedByUser.current = false;
      complete("");
    }
  }, [style, complete]);

  return (
    <>
      {/* Meta + actions */}
      <div className="flex items-center justify-between flex-wrap gap-4 mb-10">
        <div className="flex items-center gap-4 text-sm text-neutral-500">
          <span className="flex items-center gap-1.5">
            <svg
              width="14"
              height="14"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.5"
              className="opacity-40"
            >
              <circle cx="12" cy="12" r="10" />
              <polyline points="12 6 12 12 16 14" />
            </svg>
            {Math.max(1, Math.ceil(rawContent.length / 1000))} min read
          </span>
        </div>
        <CopyPageDropdown slug={meta.slug} rawContent={rawContent} aiContent={completion} showOriginal={showOriginal} viewingMarkdown={viewingMarkdown} onToggleViewMarkdown={() => setViewingMarkdown((v) => !v)} />
      </div>

      {/* Style Selector */}
      <StyleSelector
        value={style}
        onChange={handleStyleChange}
        disabled={isLoading}
      />

      {/* Status */}
      <div className="flex items-center gap-2 mb-8 text-[0.8125rem] text-neutral-500 min-h-[28px]">
        {isLoading ? (
          <>
            <span className="w-[6px] h-[6px] rounded-full bg-emerald-400 animate-pulse-dot" />
            <span>
              Generating ·{" "}
              {process.env.NEXT_PUBLIC_OPENAI_MODEL || "gpt-5-mini"}
            </span>
            <button
              onClick={stop}
              className="ml-auto text-xs px-2.5 py-1 rounded-lg border border-white/[0.06] bg-transparent text-neutral-600 hover:text-neutral-400 hover:border-white/[0.1] transition-all cursor-pointer"
            >
              Stop
            </button>
          </>
        ) : completion ? (
          <>
            <span className="text-neutral-600">
              Generated by {process.env.NEXT_PUBLIC_OPENAI_MODEL || "gpt-5-mini"}
            </span>
            <button
              onClick={generate}
              className="ml-auto text-xs px-2.5 py-1 rounded-lg border border-white/[0.06] bg-transparent text-neutral-600 hover:text-neutral-400 hover:border-white/[0.1] transition-all cursor-pointer"
            >
              Regenerate
            </button>
          </>
        ) : null}
      </div>

      {/* Error */}
      {error && (
        <div className="mb-8 p-4 border border-red-400/20 bg-red-400/5 rounded-xl text-sm text-red-400/70">
          生成に失敗しました。
          <button
            onClick={generate}
            className="underline ml-1 hover:text-red-300"
          >
            再試行
          </button>
        </div>
      )}

      {/* Content */}
      <div className="min-h-[200px]">
        {viewingMarkdown ? (
          <MarkdownSource content={showOriginal ? rawContent : (completion || rawContent)} isLoading={!showOriginal && isLoading} />
        ) : showOriginal ? (
          <StreamingContent content={rawContent} isLoading={false} />
        ) : (
          <StreamingContent content={completion} isLoading={isLoading} />
        )}
      </div>

      {/* Bottom toggle */}
      <div className="mt-14 pt-6 border-t border-white/[0.06] flex items-center justify-between">
        <div className="flex bg-white/[0.03] border border-white/[0.06] rounded-xl p-[3px]">
          <button
            onClick={() => setShowOriginal(false)}
            className={`text-[0.8125rem] px-4 py-[6px] rounded-[9px] border-none cursor-pointer transition-all ${
              !showOriginal
                ? "bg-white/[0.08] text-white"
                : "bg-transparent text-neutral-500 hover:text-neutral-300"
            }`}
          >
            AI Generated
          </button>
          <button
            onClick={() => setShowOriginal(true)}
            className={`text-[0.8125rem] px-4 py-[6px] rounded-[9px] border-none cursor-pointer transition-all ${
              showOriginal
                ? "bg-white/[0.08] text-white"
                : "bg-transparent text-neutral-500 hover:text-neutral-300"
            }`}
          >
            Original
          </button>
        </div>
      </div>
    </>
  );
}
